apiVersion: v1
kind: Service
metadata:
  name: simple-deployment-service
spec:
  type: NodePort
  selector:
    app: nginx-web-app
  ports:
      - nodePort: 31000
        protocol: TCP
        port: 80
